<--Creation of Tables-->

CREATE TABLE invoice(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	invoice_ref VARCHAR2(11) NOT NULL,
	invoice_date DATE NOT NULL,
	invoice_status VARCHAR2(10),
	hold_reason VARCHAR2(100),
	invoice_amount NUMBER(10,2),
	invoice_description VARCHAR2(500),
	order_ref VARCHAR2(10),
	PRIMARY KEY (id)
);

CREATE TABLE mcb_order (
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	order_ref VARCHAR2(10) NOT NULL,
	order_date DATE NOT NULL,
	total_amount NUMBER(10,2),
	order_description VARCHAR2(500),
	order_status VARCHAR2(10),
	line_amount NUMBER(10,2),
	supplier_name VARCHAR2(25),
	supplier_contact_name VARCHAR2(25),
	supplier_address VARCHAR2(60),
	supplier_contact_number VARCHAR2(25),
	supplier_email VARCHAR2(30),
    invoice_ref VARCHAR2(11),
	invoice_id NUMBER(10),
	PRIMARY KEY (id),
	FOREIGN KEY (invoice_id) REFERENCES invoice(id)


<--Migration Process-->

<--Populate Table INVOICE-->
INSERT INTO invoice (invoice_ref, invoice_date, invoice_status, hold_reason, invoice_amount, invoice_description, order_ref)
SELECT invoice_reference, TO_DATE(invoice_date, 'dd/mm/yyyy'),invoice_status,invoice_hold_reason,TO_NUMBER(REGEXP_REPLACE (invoice_amount, '\D')), invoice_description, order_ref
FROM xxbcm_order_mgt
WHERE invoice_reference IS NOT NULL;

<--Populate Table MCB_ORDER-->
INSERT INTO mcb_order (order_ref, order_date, total_amount, order_description, order_status, line_amount, supplier_name, supplier_contact_name, supplier_address,supplier_contact_number,supplier_email, invoice_ref)
SELECT order_ref,  TO_DATE(order_date, 'dd/mm/yyyy'), TO_NUMBER(REGEXP_REPLACE (order_total_amount, '\D')), order_description, order_status, TO_NUMBER(REGEXP_REPLACE (order_line_amount, '\D')), 
supplier_name, supp_contact_name, supp_address,supp_contact_number,supp_email,invoice_reference
FROM xxbcm_order_mgt;


<--Question 4-->
select distinct(invoice.invoice_ref), TO_CHAR(sum(invoice.invoice_amount),'FM99,999,990.00'), order_status, supplier_name, order_date, REPLACE(invoice.order_ref, 'PO0'), TO_CHAR(sum(mcb_order.total_amount),'FM99,999,990.00'),invoice_status
from invoice
INNER JOIN mcb_order ON invoice.invoice_ref = mcb_order.invoice_ref and invoice.order_ref = mcb_order.order_ref 
GROUP BY invoice.invoice_ref, order_status, supplier_name, order_date, invoice.order_ref,invoice_status
ORDER BY order_date desc;

<--Question 5-->
select order_ref,order_date,supplier_name,total_amount,order_status,invoice_ref from mcb_order 
order by total_amount desc
OFFSET 2 ROWS
fetch NEXT 1 rows only;

<--Question 6-->
select count(order_ref), TO_CHAR(sum(total_amount),'FM99,999,990.00'), supplier_name, supplier_contact_name, supplier_contact_number
from mcb_order
where order_date <= to_date('31/08/2017', 'dd/mm/yyyy') and order_date >= to_date('01/01/2017', 'dd/mm/yyyy')
group by supplier_name,supplier_contact_name,supplier_contact_number;